name: Check Dependencies

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  check-dependencies:
    uses: Telucero/workflows/.github/workflows/check-dependencies.yml@main
    permissions:
      contents: read
      issues: write  # Required for creating GitHub issues
